import { Chapter } from '@/types/index';

export const CHEMISTRY_CHAPTERS: Chapter[] = [
  {
    id: 'c1',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Mole Concept (Some Basic Concepts of Chemistry)',
    serialNumber: 'CH01',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c2',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Atomic Structure',
    serialNumber: 'CH02',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c3',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Chemical Bonding',
    serialNumber: 'CH03',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Atomic Structure'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c4',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Chemical Thermodynamics',
    serialNumber: 'CH04',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c5',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Solutions',
    serialNumber: 'CH05',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Mole Concept (Some Basic Concepts of Chemistry)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c6',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Equilibrium',
    serialNumber: 'CH06',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c7',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Redox Reactions',
    serialNumber: 'CH07',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c8',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Electrochemistry',
    serialNumber: 'CH08',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Redox Reactions'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c9',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Chemical Kinetics',
    serialNumber: 'CH09',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c10',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Surface Chemistry',
    serialNumber: 'CH10',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c11',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Solid State',
    serialNumber: 'CH11',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  // Inorganic Chemistry
  {
    id: 'c12',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'Periodic Table & Periodicity',
    serialNumber: 'CH12',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c13',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'p-Block Elements',
    serialNumber: 'CH13',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Periodic Table & Periodicity'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c14',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'd- & f-Block Elements',
    serialNumber: 'CH14',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Periodic Table & Periodicity'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c15',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'Coordination Compounds',
    serialNumber: 'CH15',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Chemical Bonding'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c16',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'Metallurgy',
    serialNumber: 'CH16',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  // Organic Chemistry
  {
    id: 'c17',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Purification & Characterisation of Organic Compounds',
    serialNumber: 'CH17',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c18',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'General Organic Chemistry (GOC)',
    serialNumber: 'CH18',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c19',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Hydrocarbons',
    serialNumber: 'CH19',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['General Organic Chemistry (GOC)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c20',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Organic Compounds Containing Halogens',
    serialNumber: 'CH20',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['General Organic Chemistry (GOC)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c21',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Organic Compounds Containing Oxygen',
    serialNumber: 'CH21',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Organic Compounds Containing Halogens'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c22',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Organic Compounds Containing Nitrogen',
    serialNumber: 'CH22',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Organic Compounds Containing Oxygen'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c23',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Biomolecules',
    serialNumber: 'CH23',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['General Organic Chemistry (GOC)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c24',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Practical Organic Chemistry (Qualitative Analysis)',
    serialNumber: 'CH24',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['General Organic Chemistry (GOC)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
];
