import { Chapter } from '@/types/index';

export const MATH_CHAPTERS: Chapter[] = [
  {
    id: 'm1',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Sets, Relations & Functions',
    serialNumber: 'CH01',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm2',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Complex Numbers',
    serialNumber: 'CH02',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Quadratic Equations'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm3',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Quadratic Equations',
    serialNumber: 'CH03',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm4',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Matrices',
    serialNumber: 'CH04',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm5',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Determinants',
    serialNumber: 'CH05',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Matrices'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm6',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Permutations & Combinations',
    serialNumber: 'CH06',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm7',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Binomial Theorem',
    serialNumber: 'CH07',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Permutations & Combinations'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm8',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Sequences & Series',
    serialNumber: 'CH08',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm9',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Mathematical Induction',
    serialNumber: 'CH09',
    weightage: 1,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm10',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Statistics',
    serialNumber: 'CH10',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm11',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Probability',
    serialNumber: 'CH11',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Permutations & Combinations', 'Sets, Relations & Functions'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm12',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Trigonometric Functions',
    serialNumber: 'CH12',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm13',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Inverse Trigonometric Functions',
    serialNumber: 'CH13',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Trigonometric Functions'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  // Geometry
  {
    id: 'm14',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Straight Lines',
    serialNumber: 'CH14',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm15',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Circles',
    serialNumber: 'CH15',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Straight Lines'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm16',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Conic Sections',
    serialNumber: 'CH16',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Circles'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm17',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Vector Algebra',
    serialNumber: 'CH17',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm18',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Three-Dimensional Geometry',
    serialNumber: 'CH18',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Vector Algebra'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  // Calculus
  {
    id: 'm19',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Limits, Continuity & Differentiability',
    serialNumber: 'CH19',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Sets, Relations & Functions'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm20',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Differentiation',
    serialNumber: 'CH20',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['Limits, Continuity & Differentiability'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm21',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Applications of Derivatives',
    serialNumber: 'CH21',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Differentiation'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm22',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Indefinite Integration',
    serialNumber: 'CH22',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Differentiation'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm23',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Definite Integration',
    serialNumber: 'CH23',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Indefinite Integration'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm24',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Differential Equations',
    serialNumber: 'CH24',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Definite Integration'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm25',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Area Under Curves',
    serialNumber: 'CH25',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Definite Integration'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  }
];
