import { Chapter } from '@/types/index';

export const PHYSICS_CHAPTERS: Chapter[] = [
  {
    id: 'p1',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Units & Measurements',
    serialNumber: 'CH01',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p2',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Kinematics',
    serialNumber: 'CH02',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Units & Measurements'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p3',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Laws of Motion',
    serialNumber: 'CH03',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Kinematics'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p4',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Work, Energy & Power',
    serialNumber: 'CH04',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p5',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Rotational Motion',
    serialNumber: 'CH05',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Laws of Motion', 'Work, Energy & Power'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p6',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Gravitation',
    serialNumber: 'CH06',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p7',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Mechanical Properties of Solids',
    serialNumber: 'CH07',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p8',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Mechanical Properties of Fluids',
    serialNumber: 'CH08',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p9',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Thermal Physics',
    serialNumber: 'CH09',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p10',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Thermodynamics',
    serialNumber: 'CH10',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Thermal Physics'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p11',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Kinetic Theory of Gases',
    serialNumber: 'CH11',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['Thermodynamics'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p12',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Oscillations (SHM)',
    serialNumber: 'CH12',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p13',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Waves',
    serialNumber: 'CH13',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Oscillations (SHM)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p14',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Electrostatics',
    serialNumber: 'CH14',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p15',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Current Electricity',
    serialNumber: 'CH15',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Electrostatics'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p16',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Magnetic Effects of Current & Magnetism',
    serialNumber: 'CH16',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Current Electricity'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p17',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Electromagnetic Induction & Alternating Current',
    serialNumber: 'CH17',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Magnetic Effects of Current & Magnetism'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p18',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Electromagnetic Waves',
    serialNumber: 'CH18',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['Electromagnetic Induction & Alternating Current'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p19',
    subject: 'physics',
    unit: 'Optics & Waves',
    name: 'Ray & Wave Optics',
    serialNumber: 'CH19',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Waves'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p20',
    subject: 'physics',
    unit: 'Optics & Waves',
    name: 'Dual Nature, Atoms & Nuclei',
    serialNumber: 'CH20',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p21',
    subject: 'physics',
    unit: 'Optics & Waves',
    name: 'Electronic Devices + Experimental Skills',
    serialNumber: 'CH21',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
];
