import { Chapter, Mistake } from '../types/index';

// Initial Database Seeding Chapters
export const INITIAL_CHAPTERS: Chapter[] = [
  // --- PHYSICS (21 Chapters) ---
  {
    id: 'p1',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Units & Measurements',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p2',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Kinematics',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Units & Measurements'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p3',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Laws of Motion',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Kinematics'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p4',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Work, Energy & Power',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p5',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Rotational Motion',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Laws of Motion', 'Work, Energy & Power'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p6',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Gravitation',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p7',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Mechanical Properties of Solids',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p8',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Mechanical Properties of Fluids',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p9',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Thermal Physics',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p10',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Thermodynamics',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Thermal Physics'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p11',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Kinetic Theory of Gases',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['Thermodynamics'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p12',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Oscillations (SHM)',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Laws of Motion'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p13',
    subject: 'physics',
    unit: 'Mechanics',
    name: 'Waves',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Oscillations (SHM)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p14',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Electrostatics',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p15',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Current Electricity',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Electrostatics'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p16',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Magnetic Effects of Current & Magnetism',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Current Electricity'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p17',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Electromagnetic Induction & Alternating Current',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Magnetic Effects of Current & Magnetism'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p18',
    subject: 'physics',
    unit: 'Electrodynamics',
    name: 'Electromagnetic Waves',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['Electromagnetic Induction & Alternating Current'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p19',
    subject: 'physics',
    unit: 'Optics & Waves',
    name: 'Ray & Wave Optics',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Waves'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p20',
    subject: 'physics',
    unit: 'Optics & Waves',
    name: 'Dual Nature, Atoms & Nuclei',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'p21',
    subject: 'physics',
    unit: 'Optics & Waves',
    name: 'Electronic Devices + Experimental Skills',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },

  // --- CHEMISTRY (24 Chapters) ---
  // Physical Chemistry
  {
    id: 'c1',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Mole Concept (Some Basic Concepts of Chemistry)',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c2',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Atomic Structure',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c3',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Chemical Bonding',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Atomic Structure'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c4',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Chemical Thermodynamics',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c5',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Solutions',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Mole Concept (Some Basic Concepts of Chemistry)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c6',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Equilibrium',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c7',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Redox Reactions',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c8',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Electrochemistry',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Redox Reactions'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c9',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Chemical Kinetics',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c10',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Surface Chemistry',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c11',
    subject: 'chemistry',
    unit: 'Physical Chemistry',
    name: 'Solid State',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  // Inorganic Chemistry
  {
    id: 'c12',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'Periodic Table & Periodicity',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c13',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'p-Block Elements',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Periodic Table & Periodicity'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c14',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'd- & f-Block Elements',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Periodic Table & Periodicity'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c15',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'Coordination Compounds',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Chemical Bonding'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c16',
    subject: 'chemistry',
    unit: 'Inorganic Chemistry',
    name: 'Metallurgy',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  // Organic Chemistry
  {
    id: 'c17',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Purification & Characterisation of Organic Compounds',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c18',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'General Organic Chemistry (GOC)',
    weightage: 6,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c19',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Hydrocarbons',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['General Organic Chemistry (GOC)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c20',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Organic Compounds Containing Halogens',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['General Organic Chemistry (GOC)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c21',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Organic Compounds Containing Oxygen',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Organic Compounds Containing Halogens'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c22',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Organic Compounds Containing Nitrogen',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Organic Compounds Containing Oxygen'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c23',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Biomolecules',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['General Organic Chemistry (GOC)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'c24',
    subject: 'chemistry',
    unit: 'Organic Chemistry',
    name: 'Practical Organic Chemistry (Qualitative Analysis)',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['General Organic Chemistry (GOC)'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },

  // --- MATHEMATICS (25 Chapters) ---
  // Algebra
  {
    id: 'm1',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Sets, Relations & Functions',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm2',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Complex Numbers',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Quadratic Equations'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm3',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Quadratic Equations',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm4',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Matrices',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm5',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Determinants',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Matrices'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm6',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Permutations & Combinations',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm7',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Binomial Theorem',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Permutations & Combinations'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm8',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Sequences & Series',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm9',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Mathematical Induction',
    weightage: 1,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm10',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Statistics',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm11',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Probability',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Permutations & Combinations', 'Sets, Relations & Functions'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm12',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Trigonometric Functions',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm13',
    subject: 'maths',
    unit: 'Algebra',
    name: 'Inverse Trigonometric Functions',
    weightage: 2,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Trigonometric Functions'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  // Geometry
  {
    id: 'm14',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Straight Lines',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm15',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Circles',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Straight Lines'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm16',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Conic Sections',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Circles'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm17',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Vector Algebra',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: [],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm18',
    subject: 'maths',
    unit: 'Geometry',
    name: 'Three-Dimensional Geometry',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Vector Algebra'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  // Calculus
  {
    id: 'm19',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Limits, Continuity & Differentiability',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Sets, Relations & Functions'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm20',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Differentiation',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Easy',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 3,
    dependencies: ['Limits, Continuity & Differentiability'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm21',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Applications of Derivatives',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Differentiation'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm22',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Indefinite Integration',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Differentiation'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm23',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Definite Integration',
    weightage: 5,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Hard',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 1,
    dependencies: ['Indefinite Integration'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm24',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Differential Equations',
    weightage: 4,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Definite Integration'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  },
  {
    id: 'm25',
    subject: 'maths',
    unit: 'Calculus',
    name: 'Area Under Curves',
    weightage: 3,
    completion: 0,
    currentLecture: 0,
    totalLectures: 0,
    theoryComplete: false,
    dppComplete: false,
    pyqsComplete: false,
    revisionCount: 0,
    difficulty: 'Medium',
    confidence: 0,
    estimatedRemainingTime: 0,
    priority: 2,
    dependencies: ['Definite Integration'],
    weaknessScore: 0,
    status: 'Not Started',
    solvedQuestions: 0,
    lastRevisionDaysAgo: 0
  }
];

// Fallback initial coach briefing message before AI Coach analysis is generated
export const DEFAULT_COACH_BRIEFING = [
  "Welcome to JEE OS. Complete your first study session to generate insights."
];

export const INITIAL_MISTAKES: Mistake[] = [];
