import { BaseActions } from './BaseActions';
import { TodayMission, Note, SubjectId } from '@/types/index';
import { CustomMissionRepository } from '@/repositories/customMissionRepository';
import { UserRepository } from '@/repositories/userRepository';
import { toLocalDateString } from '@/utils/dateUtils';
import { StudyBrainRuntime } from '@/runtime/StudyBrainRuntime';
import { TaskCompletionHandler, TaskCompletionMetrics } from './mission/TaskCompletionHandler';
import { NoteActions } from './NoteActions';

export class MissionActions extends BaseActions {
  private taskCompletionHandler: TaskCompletionHandler;
  private noteActions: NoteActions;

  constructor(runtime: StudyBrainRuntime, userId: string) {
    super(runtime, userId);
    this.taskCompletionHandler = new TaskCompletionHandler(runtime, userId);
    this.noteActions = new NoteActions(runtime, userId);
  }

  override setUserId(newUid: string) {
    super.setUserId(newUid);
    this.taskCompletionHandler.setUserId(newUid);
    this.noteActions.setUserId(newUid);
  }

  // --- Task Completion Pipeline Delegation ---
  async completeTask(
    taskId: string,
    durationSecs?: number,
    metrics?: TaskCompletionMetrics
  ) {
    return this.taskCompletionHandler.completeTask(taskId, durationSecs, metrics);
  }

  // --- Mission Management Actions ---
  async deleteMission(taskId: string) {
    this.checkWriteBlock();
    const updatedDeletedMissionIds = Array.from(new Set([...(this.state.deletedMissionIds || []), taskId]));

    const isCustom = this.state.customMissions.some(cm => cm.id === taskId);

    const updatedCustomMissions = isCustom
      ? this.state.customMissions.filter(m => m.id !== taskId)
      : this.state.customMissions;

    const updatedTodayMissions = this.state.todayMissions.filter(m => m.id !== taskId);

    const originalSnapshot = {
      todayMissions: this.state.todayMissions,
      customMissions: this.state.customMissions,
      deletedMissionIds: this.state.deletedMissionIds
    };

    this.runtime.updateStateOptimistic({
      todayMissions: updatedTodayMissions,
      customMissions: updatedCustomMissions,
      deletedMissionIds: updatedDeletedMissionIds
    });

    try {
      if (isCustom) {
        await CustomMissionRepository.deleteMission(this.userId, taskId);
      }
      await UserRepository.updateUserProfile(this.userId, { deletedMissionIds: updatedDeletedMissionIds });
      await this.runtime.refresh('SESSION_UPDATE', {
        todayMissions: updatedTodayMissions,
        customMissions: updatedCustomMissions,
        deletedMissionIds: updatedDeletedMissionIds,
        lastSyncError: null
      });
    } catch (err) {
      this.runtime.updateStateOptimistic(originalSnapshot);
      await this.handleWriteError(err, 'deleteMission');
    }
  }

  async addCustomMission(missionData: Omit<TodayMission, 'id' | 'completed' | 'unlocked'>) {
    this.checkWriteBlock();
    const newMission: TodayMission = {
      ...missionData,
      id: `user-custom-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      completed: false,
      unlocked: true,
      xp: missionData.xp || Math.round((missionData.duration || 60) * 0.5),
      priorityScore: 1.0,
      selectionReason: "Manually added by student",
      isManualOverride: true,
      timeSlot: 'Manual (Ad Hoc)'
    };

    const updatedMissions = [...this.state.todayMissions, newMission];
    const updatedCustomMissions = [...this.state.customMissions, newMission];

    const originalSnapshot = {
      todayMissions: this.state.todayMissions,
      customMissions: this.state.customMissions
    };

    this.runtime.updateStateOptimistic({
      todayMissions: updatedMissions,
      customMissions: updatedCustomMissions
    });

    try {
      await CustomMissionRepository.saveMission(this.userId, newMission);
      await this.runtime.refresh('SESSION_UPDATE', { 
        todayMissions: updatedMissions,
        customMissions: updatedCustomMissions,
        lastSyncError: null
      });
    } catch (err) {
      this.runtime.updateStateOptimistic(originalSnapshot);
      await this.handleWriteError(err, 'addCustomMission');
    }
  }

  async addAiMission(missionData: Omit<TodayMission, 'id' | 'completed' | 'unlocked'>) {
    this.checkWriteBlock();
    const newMission: TodayMission = {
      ...missionData,
      id: `mission-ai-${Date.now()}`,
      completed: false,
      unlocked: true,
      xp: missionData.xp || Math.round((missionData.duration || 60) * 0.5),
      priorityScore: 1.0,
      selectionReason: "Generated by AI Coach"
    };

    const updatedMissions = [...this.state.todayMissions, newMission];
    const updatedCustomMissions = [...this.state.customMissions, newMission];

    this.runtime.updateStateOptimistic({
      todayMissions: updatedMissions,
      customMissions: updatedCustomMissions
    });

    try {
      await CustomMissionRepository.saveMission(this.userId, newMission);
      await this.runtime.refresh('SESSION_UPDATE', { 
        todayMissions: updatedMissions,
        customMissions: updatedCustomMissions,
        lastSyncError: null
      });
    } catch (err) {
      this.runtime.rollbackMission(newMission.id, null);
      this.runtime.updateStateOptimistic({
        customMissions: this.state.customMissions.filter(m => m.id !== newMission.id)
      });
      await this.handleWriteError(err, 'addAiMission');
    }
  }

  async updateMissionDetails(taskId: string, updates: Partial<TodayMission>) {
    this.checkWriteBlock();
    
    const missionIndex = this.state.todayMissions.findIndex(m => m.id === taskId);
    if (missionIndex === -1) return;

    const mission = this.state.todayMissions[missionIndex];
    const updatedMission = { 
      ...mission, 
      ...updates, 
      xp: updates.duration ? Math.round(updates.duration * 0.5) : mission.xp
    };
    
    const updatedMissions = [...this.state.todayMissions];
    updatedMissions[missionIndex] = updatedMission;
    
    const isCustom = this.state.customMissions.some(cm => cm.id === taskId);
    const updatedCustomMissions = isCustom
      ? this.state.customMissions.map(cm => cm.id === taskId ? updatedMission : cm)
      : this.state.customMissions;

    const originalSnapshot = {
      todayMissions: this.state.todayMissions,
      customMissions: this.state.customMissions
    };

    this.runtime.updateStateOptimistic({
      todayMissions: updatedMissions,
      customMissions: updatedCustomMissions
    });
    
    try {
      if (isCustom) {
        await CustomMissionRepository.saveMission(this.userId, updatedMission);
      }
      
      await this.runtime.refresh('SESSION_UPDATE', {
        todayMissions: updatedMissions,
        customMissions: updatedCustomMissions,
        lastSyncError: null
      });
    } catch (err) {
      this.runtime.updateStateOptimistic(originalSnapshot);
      await this.handleWriteError(err, 'updateMissionDetails');
    }
  }

  async skipTask(taskId: string) {
    this.checkWriteBlock();
    const missionIndex = this.state.todayMissions.findIndex(m => m.id === taskId);
    if (missionIndex === -1) return;

    const updatedMissions = [...this.state.todayMissions];
    updatedMissions[missionIndex] = {
      ...updatedMissions[missionIndex],
      dismissed: true
    };

    if (missionIndex + 1 < updatedMissions.length) {
      updatedMissions[missionIndex + 1] = {
        ...updatedMissions[missionIndex + 1],
        unlocked: true
      };
    }

    const skippedMission = updatedMissions[missionIndex];
    const isCustomOrPrefixed = skippedMission.id.startsWith('mission-') || skippedMission.id.includes('custom');
    const updatedDismissedPlannerMissionIds = !isCustomOrPrefixed
      ? Array.from(new Set([...(this.state.dismissedPlannerMissionIds || []), taskId])).slice(-1000)
      : this.state.dismissedPlannerMissionIds;

    const originalSnapshot = {
      todayMissions: this.state.todayMissions,
      dismissedPlannerMissionIds: this.state.dismissedPlannerMissionIds
    };

    this.runtime.updateStateOptimistic({
      todayMissions: updatedMissions,
      ...(!isCustomOrPrefixed ? { dismissedPlannerMissionIds: updatedDismissedPlannerMissionIds } : {})
    });

    try {
      const savePromises = [];

      if (isCustomOrPrefixed) {
        savePromises.push(this.safeDbCall(() => CustomMissionRepository.saveMission(this.userId, skippedMission), 'saveMission'));
      } else {
        savePromises.push(this.safeDbCall(() => UserRepository.updateUserProfile(this.userId, { dismissedPlannerMissionIds: updatedDismissedPlannerMissionIds }), 'updateUserProfile'));
      }

      await Promise.all(savePromises);
      await this.runtime.refresh('SESSION_UPDATE', { 
        todayMissions: updatedMissions,
        ...(!isCustomOrPrefixed ? { dismissedPlannerMissionIds: updatedDismissedPlannerMissionIds } : {}),
        lastSyncError: null
      });
    } catch (err) {
      this.runtime.updateStateOptimistic(originalSnapshot);
      await this.handleWriteError(err, 'skipTask');
    }
  }

  async addTodayMission(mission: TodayMission) {
    const missionWithOverrides: TodayMission = {
      ...mission,
      unlocked: true,
      isManualOverride: true,
      scheduledDate: mission.scheduledDate || toLocalDateString()
    };
    const updatedToday = [...(this.state.todayMissions || []).filter(m => m.id !== mission.id), missionWithOverrides];
    const updatedCustom = [...(this.state.customMissions || []).filter(m => m.id !== mission.id), missionWithOverrides];

    const originalSnapshot = {
      todayMissions: this.state.todayMissions,
      customMissions: this.state.customMissions
    };

    this.runtime.updateStateOptimistic({
      todayMissions: updatedToday,
      customMissions: updatedCustom
    });

    try {
      await this.safeDbCall(
        () => CustomMissionRepository.saveMission(this.userId, missionWithOverrides),
        'addTodayMission'
      );
      await this.runtime.refresh('SESSION_UPDATE', {
        todayMissions: updatedToday,
        customMissions: updatedCustom,
        lastSyncError: null
      });
    } catch (err) {
      this.runtime.updateStateOptimistic(originalSnapshot);
      await this.handleWriteError(err, 'addTodayMission');
    }
  }

  async clearTodayMissions() {
    this.runtime.updateStateOptimistic({ todayMissions: [] });
    await this.runtime.refresh('SESSION_UPDATE', { todayMissions: [] });
  }

  async rebalancePlan() {
    this.checkWriteBlock();

    const emptyOverrides = {};

    const now = new Date();
    const currentDayIndex = (now.getDay() + 6) % 7;

    // Filter out synthetic auto-generated breaks before rebalancing.
    // generateWeeklyMatrix will freshly regenerate and interleave breaks between sessions.
    const nonAutoBreakMissions = (this.state.todayMissions || []).filter(m => 
      !(m.subject === 'break' && (m.id.startsWith('break-') || m.id.startsWith('today-break-')) && !m.isManualOverride)
    );
    
    const extractLecNum = (name: string): number => {
      const match = (name || '').match(/Lecture\s+(\d+)/i);
      return match ? parseInt(match[1], 10) : Number.MAX_SAFE_INTEGER;
    };

    const sortedMissions = [...nonAutoBreakMissions].sort((a, b) => {
      if (a.completed !== b.completed) return a.completed ? -1 : 1;
      if (a.dismissed !== b.dismissed) return a.dismissed ? 1 : -1;
      if (a.isManualOverride && !b.isManualOverride) return -1;
      if (!a.isManualOverride && b.isManualOverride) return 1;

      const sameChapter = (a.chapter || '').toLowerCase() === (b.chapter || '').toLowerCase();
      const aIsLec = (a.type === 'Watch Lecture' || /Lecture\s+\d+/i.test(a.taskName || ''));
      const bIsLec = (b.type === 'Watch Lecture' || /Lecture\s+\d+/i.test(b.taskName || ''));
      if (sameChapter && aIsLec && bIsLec) {
        const diff = extractLecNum(a.taskName) - extractLecNum(b.taskName);
        if (diff !== 0) return diff;
      }

      const prioDiff = (b.priorityScore || 0) - (a.priorityScore || 0);
      if (prioDiff !== 0) return prioDiff;

      return (a.id || '').localeCompare(b.id || '');
    });

    const cleanedMissions = sortedMissions.map(m => {
      if (!m.completed && !m.isManualOverride) {
        return {
          ...m,
          timeSlot: undefined,
          isManualOverride: false
        };
      }
      return m;
    });

    const { generateWeeklyMatrix } = await import('@jee-os/engines');
    const rawQuota = this.state.settings?.dailyQuota || 6.5;
    const baseDailyHours = (rawQuota > 14) ? 4.5 : Math.max(2.0, rawQuota);
    const energyMultiplier = this.state.energyLevel === 'Low' ? 0.5 : this.state.energyLevel === 'Medium' ? 1.0 : 1.25;
    const totalDailyQuotaHours = Math.round(baseDailyHours * energyMultiplier * 10) / 10;

    const matrixSettings = {
      ...(this.state.settings || {}),
      energyLevel: this.state.energyLevel,
      effectiveDailyStudyHours: totalDailyQuotaHours,
      dailyCapHours: totalDailyQuotaHours
    };
    const updatedWeekly = generateWeeklyMatrix(
      this.state.mentorProfile?.subjectSplitStrategy || '3_a_day',
      this.state.chapters,
      cleanedMissions,
      null,
      currentDayIndex,
      this.state.mentorProfile?.twoDaySplitConfig,
      this.state.deletedMissionIds || [],
      emptyOverrides,
      this.state.settings?.dayStartTime || "07:00",
      this.state.settings?.dayEndTime || "22:30",
      matrixSettings
    );

    const currentDayBlocks = updatedWeekly.filter(b => b.dayIndex === currentDayIndex);
    
    let updatedTodayMissions: TodayMission[];
    if (updatedWeekly.length === 0 && cleanedMissions.length > 0) {
      updatedTodayMissions = cleanedMissions;
    } else {
      updatedTodayMissions = currentDayBlocks.map(b => {
        const originalId = b.id.startsWith('today-') ? b.id.slice(6) : b.id;
        const original = cleanedMissions.find(m => m.id === originalId);
        const mappedSubject: SubjectId | 'break' = 
          b.subject === 'break' 
            ? 'break' 
            : (b.subject === 'physics' || b.subject === 'chemistry' || b.subject === 'maths')
            ? b.subject as SubjectId
            : (original?.subject && original.subject !== 'break')
            ? original.subject
            : (this.state.chapters?.find(c => c.id === b.chapterId || c.name === b.chapterName)?.subject || 'physics');

        return {
          id: originalId,
          subject: mappedSubject,
          chapter: b.chapterName,
          chapterId: b.chapterId,
          type: b.taskType,
          taskName: b.activity,
          duration: b.durationMinutes,
          timeSlot: b.timeSlot,
          completed: original ? original.completed : b.completed,
          xp: original ? original.xp : Math.round(b.priorityScore),
          unlocked: true,
          priorityScore: b.priorityScore,
          reasoning: b.reasoning,
          dismissed: original?.dismissed ?? false,
          isManualOverride: false,
          scheduledDate: b.scheduledDate,
          scheduledTime: b.scheduledTime
        };
      });
    }

    const originalSnapshot = {
      scheduleOverrides: this.state.scheduleOverrides,
      todayMissions: this.state.todayMissions,
      weeklySchedule: this.state.weeklySchedule
    };

    this.runtime.updateStateOptimistic({
      scheduleOverrides: emptyOverrides,
      todayMissions: updatedTodayMissions,
      weeklySchedule: updatedWeekly
    });

    try {
      await this.safeDbCall(() => UserRepository.updateUserProfile(this.userId, { scheduleOverrides: emptyOverrides }), 'updateUserProfile');
      await this.runtime.refresh('INIT', {
        scheduleOverrides: emptyOverrides,
        todayMissions: updatedTodayMissions,
        weeklySchedule: updatedWeekly
      });
    } catch (err) {
      this.runtime.updateStateOptimistic(originalSnapshot);
      await this.handleWriteError(err, 'rebalancePlan');
    }
  }

  async resetCustomMissions() {
    this.checkWriteBlock();
    const originalSnapshot = {
      todayMissions: this.state.todayMissions
    };
    this.runtime.updateStateOptimistic({ todayMissions: [] });
    try {
      await this.runtime.refresh('INIT', { todayMissions: [] });
    } catch (err) {
      this.runtime.updateStateOptimistic(originalSnapshot);
      await this.handleWriteError(err, 'resetCustomMissions');
    }
  }

  // --- Notes & Reflections Delegation (Backward-Compatible Forwarders) ---
  async addNote(noteData: Omit<Note, 'id' | 'timestamp'> & { id?: string; timestamp?: string }) {
    return this.noteActions.addNote(noteData);
  }

  async addProofOfWorkNote(params: {
    text: string;
    subject: SubjectId;
    chapter: string;
    chapterId?: string;
    missionId?: string;
    xpWager?: number;
  }) {
    return this.noteActions.addProofOfWorkNote(params);
  }

  async deleteNote(noteId: string) {
    return this.noteActions.deleteNote(noteId);
  }
}
